batch_size: 50
embedding_dim: 400
hidden_dim: 256
n_layers: 2
output_size: 1
epochs: 3
print_every: 100
gradient_clipping: 5
learning_rate: 0.0005
dropout_prob_1: 0.5
dropout_prob_2: 0.3
seq_length: 500
split_frac: 0.6
num_heads: 8
