wandb_version: 1

batch_size:
  desc: null
  value: 50
embedding_dim:
  desc: null
  value: 400
hidden_dim:
  desc: null
  value: 256
n_layers:
  desc: null
  value: 2
output_size:
  desc: null
  value: 1
epochs:
  desc: null
  value: 4
gradient_clipping:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723113208
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.12.3
      5: 0.17.6
      8:
      - 5
      13: linux-x86_64
